[workspace]

[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_aio_db = "0.6.1"
env_logger = "0.11.3"
tokio = "1.37.0"
bevy_reflect = "0.13.1"
actix-web = "4.5.1"