[workplace]
exclude = ["example/*", "benches/*"]

[package]
name = "rs_aio_db"
version = "0.5.10"
edition = "2021"
repository = "https://github.com/milen-denev/rs_aio_db"
license = "Apache-2.0"
keywords = ["database", "libsql", "sqlite"]
authors = ["Milen Denev"]
description = "All in one (aka Aio) database with async support. Based on libsql/Sqlite, bevy_reflect and tokio, includes a dead simple API to be used (no SQL needed just pure Rust). Comes with automigration."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql = "0.3.5"
bevy_reflect = "0.13.2"
tokio = "1.37.0"
log = "0.4.21"
env_logger = "0.11.3"
stopwatch = "0.0.7"
r2d2 = "0.8.10"
serde = "1.0.198"
bincode = "1.3.3"
hex = "0.4.3"